### ISSUE TITLE
Arbitrary horizontal/vertical scrolling causes loss of sight of spindlecontent

### ISSUE THREAD

**Issue by Dwergje** [Fdebijl/spindlejs#2]
Het eerder besproken scroll issue waarbij de Spindles "Disalignen".
Het tweede besproken deel waarbij je de bug in de volgende stappen reproduceerd:
- Druk middelste muisknop in
- Sleep de muis naar rechts of naar links
Gevolg: Spindles verdwijnen
- Bij het opnieuw scrollen of indrukken van de pijltjestoetsen verschijnen de spindles weer.

**Comment by Fdebijl** [comment]
Fixed by implementation of dotnav and hashnav
