### ISSUE TITLE
New Layout glitch

### ISSUE THREAD

**Issue by Dwergje** [Fdebijl/spindlejs#3]
De nieuwe layout ziet er super strak uit, helaas brengt dit wel problemen met zich mee.

Er zijn momenteel 4 spindles en 4 bolletjes,
Als ik op het 2e bolletje druk, gaat hij naar spindle 2, maar bolletje 1 licht op.
Hetzelfde geld voor 3e bolletje, naar spindle 4, maar bolletje 2 licht op.

Hieruit kan ik de conclusie trekken dat elk bolletje oplicht voor de pagina ervoor

Specificaties: 
Browser: Google Chrome
Resolutie: 1920x1080
OS: Windows 10 
Bron: https://gyazo.com/66923b8578bfa7448e266970d769929a

**Comment by Fdebijl** [comment]
numhash + 1 in dotnav menu > probleem opgelost
